apiVersion: v1
kind: Namespace
metadata:
  name: med-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: med-config

data:
  DB_HOST: "postgres-svc"
  DB_USER: "postgres"
  DB_PASS: "password"
  RABBIT_HOST: "rabbitmq-svc"
  RABBIT_USER: "user"
  RABBIT_PASS: "password"
  S3_ENDPOINT: "http://minio-svc:9000"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  IMAGING_URL: "http://imaging-service-svc:8082/api/images"