apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: med-ns
spec:
  template:
    spec:
      containers:
        - name: create-bucket
          image: minio/mc
          command:
            - /bin/sh
            - -c
            - |
              echo "Connecting to MinIO..."
              until /usr/bin/mc alias set myminio http://minio-svc:9000 minioadmin minioadmin; do
                echo "MinIO not ready yet... waiting 5s"
                sleep 5
              done;
              
              echo "MinIO is ready! Creating bucket..."
              /usr/bin/mc mb myminio/med-staging || true;
              
              echo "Setting policy..."
              /usr/bin/mc anonymous set public myminio/med-staging;
              
              echo "Done!"
              exit 0;
      restartPolicy: OnFailure