apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: med-gateway

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # --- PATIENT SERVICE ---
          - path: /api/patient
            pathType: Prefix
            backend:
              service:
                name: patient-service-svc
                port:
                  number: 8080

          # --- IMAGING SERVICE ---
          - path: /api/images
            pathType: Prefix
            backend:
              service:
                name: imaging-service-svc
                port:
                  number: 8082

          # --- RADIOLOGY SERVICE ---
          - path: /api/radiology
            pathType: Prefix
            backend:
              service:
                name: radiology-service-svc
                port:
                  number: 8081

          # --- NOTIFICATION SERVICE ---
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service-svc
                port:
                  number: 8084