server:
  port: 8083

spring:
  application:
    name: analytical-model
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:user}
    password: ${RABBIT_PASS:password}

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin}
  bucket: med-staging
  region: us-east-1